<script src="/js/highcharts.js"></script>
<?php

function nomeMes($mes) {
    $nome = '';
    switch ($mes) {
        case 1:
            $nome = 'Janeiro';
            break;
        case 2:
            $nome = 'Fevereiro';
            break;
        case 3 :
            $nome = 'Março';
            break;
        case 4:
            $nome = 'Abril';
            break;
        case 5:
            $nome = 'Maio';
            break;
        case 6:
            $nome = 'Junho';
            break;
        case 7:
            $nome = 'Julho';
            break;
        case 8:
            $nome = 'Agosto';
            break;
        case 9:
            $nome = 'Setembro';
            break;
        case 10:
            $nome = 'Outubro';
            break;
        case 11:
            $nome = 'Novembro';
            break;
        case 12:
            $nome = 'Dezembro';
            break;
    }
    return $nome;
}
?>

<div class="row-fluid">

    <div class="span3">
        <?php include_once(__DIR__ . '/../menu.phtml'); ?>


    </div>
    <div class="span9">
        <h3>Impressões de <?php
            list($dia, $mes, $ano) = explode('-', $this->periodo);
            $titulo = " {$user} em";
            $titulo .= " {$dia} de " . nomeMes($mes) . " $ano";
            echo $titulo;
            ?></h3>

        <table class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>
                    <th>Documento</th>
                    <th>Folhas Impressas</th>
                    <th>Usuário</th>
                </tr>
            </thead>
            <tbody>
<?php $i = 0;
foreach ($this->dados as $dia => $impressoes): ?>
                    <tr>
                        <td><?php echo htmlentities(str_replace('"', '', $dia)); ?></td>
                        <td><?php echo $impressoes ?></td>

                        <td><?php echo $this->users[$i] ?></td>
                    </tr>
    <?php $i++;
endforeach; ?>

            </tbody>
            <tfoot>
                <tr  align="center">

                </tr>
            </tfoot>

        </table>
    </div>
</div>