<div class="row-fluid">

    <div class="span3">
       <?php
        
        include_once(__DIR__ . '/../menu.phtml'); ?>

    </div>
    <div class="span9">
        <table class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>
                    <th>Mês</th>
                    <th>Ano</th>
                    <th>Total</th>

                </tr>
            </thead>
            <tbody>
                <?php for ($i=0;$i<count($this->periodos['mes']);$i++): ?>
                    <tr>
                        <td><a href="<?php echo $this->url('ti/impressao/impressao-periodo',array('mes'=>$this->periodos['mes'][$i] ,'ano'=>$this->periodos['ano'][$i]));?>"><?php echo $this->periodos['mes'][$i] ?></a></td>
                        <td><?php echo $this->periodos['ano'][$i]  ?></td>
                        <td><?php echo $this->periodos['total'][$i]  ?></td>


                    </tr>
                <?php endfor; ?>

            </tbody>
            <tfoot>
                <tr  align="center">
                    
                </tr>
            </tfoot>

        </table>

    </div>
</div>