<script>
    $(document).ready(function() {
        $("table a").tooltip();
    });
</script>

<?php if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">

    <div class="span3">
        <?php include_once(__DIR__ . '/../menu.phtml'); ?>

    </div>
    <div class="span9">
<!--        <table class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>
                   
                    <th>Equipamento</th>
                    <th>Tipo</th>                   
                    <th>Opções</th>

                </tr>
            </thead>
            <tbody>
               
                    <tr>
                       
                     

                    </tr>
               

            </tbody>
            <tfoot>
                <tr  align="center">
                    <td colspan="3" >
                       
                     
                    </td>
                   
                </tr>
            </tfoot>

        </table>-->

        <h3>
            <?php
            $nome = "Descrição Física para: IRM/";
            $primeiro = $this->peca[0];
            $nome .= "{$primeiro->getEquipamentoFk()->getModeloequipamento()->getTipoequipamento()->getSigla()}/";
            $nome .= "{$primeiro->getEquipamentoFk()->getNome()}";
            echo $nome;
            ?>

        </h3>
        <br/>
        <table class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>

                    <th>Caracteristica</th>
                    <th>Detalhe</th>      
                </tr>
            </thead>
            <tbody>   
                <?php
                foreach ($this->peca as $iterator):
                    ?>
                    <tr>
                        <td>
                            <?php echo $iterator->getCaracteristicasFk()->getCaracteristica(); ?>
                        </td>
                        <td>
                            <?php echo $iterator->getDetalhe(); ?>
                        </td>
                    </tr>
                <?php endforeach; ?>

            </tbody>
            <tfoot>
                <tr  align="center">
                    <td colspan="2" >


                    </td>

                </tr>
            </tfoot>

        </table>
    </div>
</div>