<script src="/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $("table a").tooltip();
        $("#tabela").dataTable();
        $("#tabela_paginate a").addClass('btn').css({'margin-left':'5px'});
    });
</script>
<style>
    .dataTables_filter,.dataTables_length{
        width:40%;
        float:left;
    }
    #tabela_info{
        width:40%;
        float:left;
    }
    #tabela
    {
        width:100%;
        float:left;
    }
    #tabela th
    {
        cursor: pointer;
    }

    #tabela_paginate{
        float:left;
        width:35%;
    }
    #tabela_paginate a{
        float:left;        
    }
</style>
<?php if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
    <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
    <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">

    <div class="span3">
        <?php
        
        include_once(__DIR__ . '/../menu.phtml'); ?>

    </div>
    <div class="span9">
        <table id="tabela" class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>
                   
                    <th>Equipamento</th>
                    <th>Modelo</th>                   
                    <th>Tipo</th>                   
                    <th>Fabricante</th>                   
                    <th>Opções</th>

                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->fab as $usuario): ?>
                    <tr>
                       
                        <td><?php echo $usuario->getNome(); ?></td>
                        <td><?php echo $usuario->getModeloequipamento()->getModelo(); ?></td>                      
                        <td><?php echo $usuario->getModeloequipamento()->getTipoequipamento()->getNome(); ?></td>                      
                        <td><?php echo $usuario->getModeloequipamento()->getFabricantes()->getFabricante(); ?></td>                      
                        <td>
                           
                             <a href="<?php echo $this->url('ti/equipamentos/get-detalhe',array('id'=>$usuario->getIdequipamento()));?>" data-toggle="tooltip" title="Descrição do equipamento"  class="btn"><i class="icon-th-list"></i></a>
                             <a href="<?php echo $this->url('ti/equipamentos/upload-equipamento', array('id' => $usuario->getIdequipamento())); ?>" data-toggle="tooltip" title="Adicionar imagem de equipamento"  class="btn"><i class="icon-picture"></i></a>
                        </td>


                    </tr>
                <?php endforeach; ?>

            </tbody>
            <tfoot>
                <tr  align="center">
                    <td colspan="5" >
                       
                        <a data-toggle="tooltip" title="Adicionar registro"   href="<?php echo $this->url('ti/equipamentos/store');?>" class="btn btn-primary"><i class="icon-plus icon-white"></i></a>
                    </td>
                   
                </tr>
            </tfoot>

        </table>

    </div>
</div>