<script>
    $(document).ready(function() {
        $("table a").tooltip();
    });
</script>

<?php if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
    <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
    <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">

    <div class="span3">
        <?php
        
        include_once(__DIR__ . '/../menu.phtml'); ?>

    </div>
    <div class="span9">
        <table class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>
                   
                    <th>Equipamento</th>
                    <th>Modelo</th>                   
                    <th>Tipo</th>                   
                    <th>Fabricante</th>                   
                    <th>Opções</th>

                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->fab as $usuario): ?>
                    <tr>
                       
                        <td><?php echo $usuario->getNome(); ?></td>
                        <td><?php echo $usuario->getModeloequipamento()->getModelo(); ?></td>                      
                        <td><?php echo $usuario->getModeloequipamento()->getTipoequipamento()->getNome(); ?></td>                      
                        <td><?php echo $usuario->getModeloequipamento()->getFabricantes()->getFabricante(); ?></td>                      
                        <td>
                             <a href="<?php echo $this->url('ti/equipamentos/store',array('id'=>$usuario->getIdequipamento()));?>" data-toggle="tooltip" title="Editar registro"  class="btn"><i class="icon-pencil"></i></a>
                             <a href="<?php echo $this->url('ti/equipamentos/descricao-logica',array('id'=>$usuario->getIdequipamento()));?>" data-toggle="tooltip" title="Descrição lógica"  class="btn"><i class="icon-list-alt"></i></a>
                             <a href="<?php echo $this->url('ti/equipamentos/descricao-fisica',array('id'=>$usuario->getIdequipamento()));?>" data-toggle="tooltip" title="Descrição física"  class="btn"><i class="icon-wrench"></i></a>
                        </td>


                    </tr>
                <?php endforeach; ?>

            </tbody>
            <tfoot>
                <tr  align="center">
                    <td colspan="5" >
                       
                        <a data-toggle="tooltip" title="Adicionar registro"   href="<?php echo $this->url('ti/equipamentos/store');?>" class="btn btn-primary"><i class="icon-plus icon-white"></i></a>
                    </td>
                   
                </tr>
            </tfoot>

        </table>

    </div>
</div>