<div id="dropbox">
			<span class="message">Drop images here to upload. <br /><i>(they will only be visible to you)</i></span>
		</div>
		
               <link rel="stylesheet" href="/css/styles.css" />
        
        <!-- Including The jQuery Library -->
		
		<!-- Including the HTML5 Uploader plugin -->
		<script src="/js/jquery.filedrop.js"></script>
		
		<!-- The main script file -->
        <script src="/js/script.js"></script>
    