<script src="/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $("table a").tooltip();
        $("#tabela").dataTable();
    });
</script>
<style>
    .dataTables_filter,.dataTables_length{
        width:40%;
        float:left;
    }
    #tabela_info{
        width:45%;
        float:left;
    }
    #tabela
    {
        width:100%;
        float:left;
    }
    #tabela th
    {
        cursor: pointer;
    }

    #tabela_paginate{
        float:left;
        width:40%;
    }
    #tabela_paginate a{
        float:left;
        width:20%;
        cursor: pointer;
    }
</style>
<?php

use Zend\Debug\Debug;
use \DateTime;

if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">

    <div class="span3">
        <?php include_once(__DIR__ . '/../menu.phtml'); ?>


    </div>
    <div class="span9">
        <table id="tabela" class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>

                    <th>ID</th>
                    <th>Título</th>
                    <th>Data de Abertura</th>
                    <th>Previsão</th>

                    <th>Conclusão</th>
                    <th>Prioridade</th>
                    <th>Status</th>
                    <th>Nota</th>
                    <th>Tempo de atendimento</th>


                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $chamado): ?>
                    <tr>
                        <td><?php echo $chamado->getIdchamado(); ?></td>
                        <td><a href="<?php echo $this->url('ti/helpdesk/chamado', array('chamado' => $chamado->getIdchamado())); ?>"><?php echo $chamado->getTitulo(); ?></a></td>
                        <td><?php
                            $ex1 = explode(' ', $chamado->getDatainicio());
                            echo $ex1[0];
                            ?></td>
                        <td><?php
                            $ex2 = explode(' ', $chamado->getPrevisao());
                            echo $ex2[0];
                            ?></td>

                        <td><?php
                            $ex3 = explode(' ', $chamado->getDatafim());
                            echo $ex3[0];
                            ?></td>
                        <td><?php echo $chamado->getPrioridade_fk()->getPrioridade(); ?></td>
                        <td><?php
                            $d = new DateTime(implode('-', array_reverse(explode('/', reset(explode(' ', $chamado->getPrevisao()))))));

                            $dif = $date->diff($d);

                            if ($dif->format('%R%a') < 0 && $chamado->getStatuschamado_fk()->getStatus() != 'Fechado') {
                                echo '<span class="label label-important">Importante</span>';
                            } else {
                                if ($chamado->getStatuschamado_fk()->getStatus() == 'Fechado') {
                                    echo '<span class="label label-success">Fechado</span>';
                                } else {
                                    echo '<span class="label label-warning">Aberto</span>';
                                }
                            }
                            ?></td>
                        <td><?php echo $chamado->getNota(); ?></td>
                        <td><?php
                            $di = new DateTime(implode('-', array_reverse(explode('/', reset(explode(' ', $chamado->getDatainicio()))))));
                            $df = new DateTime(implode('-', array_reverse(explode('/', reset(explode(' ', $chamado->getDatafim()))))));

                            $dif = $di->diff($df);
                             $dias =  $dif->format('%d dias, %hhs %imin %sseg');
                            echo $dias <= 5 ? "<span class=\"badge badge-info\">{$dias}</span>" : "<span class=\"badge badge-important\">{$dias}</span>";
                            ?></td>

                    </tr>
<?php endforeach; ?>
            <tfoot>
                <tr>
                    <td colspan="8"><?php echo( count($this->paginator) > 0 ) ? $this->paginationControl($this->paginator, 'Sliding', 'ti/help-desk/pager.phtml', array('setor' => $setor)) : ""; ?></td>
                    <td>  <a class="btn btn-primary" href="<?php echo $this->url('ti/helpdesk/open'); ?>"><i class="icon-plus icon-white"></i> Abrir</a></td>
                </tr>
            </tfoot>
            </tbody>

        </table>


    </div>
</div>