<?php

use Zend\Debug\Debug;
use \DateTime;

if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
        <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">
  
    <div class="span3">
       <?php
        
        include_once(__DIR__ . '/../menu.phtml'); ?>
       
    </div>
    <div class="span9">
        <table class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>

                    <th>Título</th>
                    <th>Data de Abertura</th>
                    <th>Previsão</th>

                    <th>Conclusão</th>
                    <th>Prioridade</th>
                    <th>Status</th>


                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $chamado): ?>
                    <tr>

                        <td><a href="<?php echo $this->url('ti/helpdesk/chamado', array('chamado' => $chamado->getIdchamado())); ?>"><?php echo $chamado->getTitulo(); ?></a></td>
                        <td><?php echo $chamado->getDatainicio(); ?></td>
                        <td><?php echo $chamado->getPrevisao(); ?></td>

                        <td><?php echo $chamado->getDatafim() ?></td>
                        <td><?php echo $chamado->getPrioridade_fk()->getPrioridade(); ?></td>
                        <td><?php
                            $d = new DateTime(implode('-', array_reverse(explode('/', reset(explode(' ', $chamado->getPrevisao()))))));

                            $dif = $date->diff($d);

                            if ($dif->format('%R%a') < 0 && $chamado->getStatuschamado_fk()->getStatus() != 'Fechado') {
                                echo '<span class="label label-important">Importante</span>';
                            } else {
                                if ($chamado->getStatuschamado_fk()->getStatus() == 'Fechado') {
                                    echo '<span class="label label-success">Fechado</span>';
                                } else {
                                    echo '<span class="label label-warning">Aberto</span>';
                                }
                            }
                            ?></td>


                    </tr>
                <?php endforeach; ?>
            <tfoot>
                <tr>
                    <td colspan="5"><?php echo( count($this->paginator) > 0 ) ? $this->paginationControl($this->paginator, 'Sliding', 'ti/help-desk/pager.phtml', array('setor' => $setor)) : ""; ?></td>
                    <td>  <a class="btn btn-primary" href="<?php echo $this->url('ti/helpdesk/open'); ?>"><i class="icon-plus icon-white"></i> Abrir</a></td>
                </tr>
            </tfoot>
            </tbody>

        </table>


    </div>
</div>