<div class="row-fluid">

    <div class="span3">
       <?php
        
        include_once(__DIR__ . '/../menu.phtml'); ?>


    </div>
    <div class="span9">        
        <table class="table table-bordered">
            <thead>
            <th>Total de chamados</th>
            <th>Média total</th>
            <th>Chamados não avaliados</th>
            </thead>
            <tbody>
                <tr>
                    <td><?php echo $this->total_chamados; ?></td>
                    <td><?php echo $this->media; ?></td>
                    <td><?php echo $this->chamados_na; ?></td>
                </tr>
            </tbody>
        </table>
        <table class="table table-bordered">
            <thead>
            <th>Chamado</th>
            <th>Finalizado</th>
            <th>Autor</th>
            </thead>
            <tbody>
                <?php foreach($this->chamados as $chamado):?>
                <tr>
                    <td><a href="<?php echo $this->url('ti/helpdesk/chamado',array('chamado'=>$chamado->getIdchamado())); ?>"><?php echo $chamado->getTitulo(); ?></a></td>
                    <td><?php echo $chamado->getDatafim(); ?></td>
                    <td><?php echo $chamado->getAutor(); ?></td>
                </tr>
                 <?php endforeach;?>
               
            </tbody>
        </table>
        
    </div>
</div>