 <ul class="nav nav-list">
            <li class="nav-header">HelpDesk</li>
            <li><a href="<?php echo $this->url('ti/helpdesk'); ?>">Página principal</a></li>
            <li class=""><a href="<?php echo $this->url('ti/helpdesk/indicadores'); ?>">Indicadores</a></li>
            <li><a href="<?php echo $this->url('item-avaliacao-chamado',array('setor'=>1)); ?>">Itens de avaliação de chamados</a></li>
            <li class="nav-header">Impressão</li>
            <li><a href="<?php echo $this->url('ti/impressao'); ?>">Relatório</a></li>
            <li class="nav-header">Inventário</li>
            <li><a href="<?php echo $this->url('ti/fabricantes'); ?>">Fabricantes</a></li>
              <li><a href="<?php echo $this->url('ti/tipo-equipamento'); ?>">Tipos de Equipamento</a></li>
            <li><a href="<?php echo $this->url('ti/modelo-equipamento'); ?>">Modelos de Equipamento</a></li>          
            <li><a href="<?php echo $this->url('ti/softwares'); ?>">Softwares</a></li>
            <li><a href="<?php echo $this->url('ti/licencas'); ?>">Licenças</a></li>
            <li><a href="<?php echo $this->url('ti/caracteristicas'); ?>">Caracteristicas de equipamento</a></li>
            <li><a href="<?php echo $this->url('ti/equipamentos'); ?>">Equipamentos</a></li>
            <li><a href="<?php echo $this->url('ti/alocacao'); ?>">Alocação de Equipamentos</a></li>
        </ul>

