
<script src="/js/jquery.dataTables.min.js"></script>
<script>
    $(document).ready(function() {
        $("table a").tooltip();
        $("#tabela").dataTable();
    });
</script>
<style>
    .dataTables_filter,.dataTables_length{
        width:40%;
        float:left;
    }
    #tabela_info{
        width:45%;
        float:left;
    }
    #tabela
    {
        width:100%;
        float:left;
    }
    #tabela th
    {
        cursor: pointer;
    }

    #tabela_paginate{
        float:left;
        width:40%;
    }
    #tabela_paginate a{
        float:left;
        width:20%;
        cursor: pointer;
    }
</style><div class="row-fluid">

    <div class="span3">
        <?php
        
        include_once(__DIR__ . '/../menu.phtml'); ?>


    </div>
    <div class="span9">
 <table id="tabela" class="table table-striped table-bordered table-hover">
            <thead>         
             
                <tr>
                   
                    <th>ID</th>
                    <th>Colaborador</th>
                    <th>Setor</th>                   
                    <th>Local</th>                   
                    <th>Data de início</th>                   
                    <th>Finalizado</th>                   
                    <th>Registro de realocação</th>
                    <th>Observação</th>
                    <th>Equipamento</th>
                    <th>Opções</th>

                </tr>
               
            </thead>
            <tbody>
                  <?php foreach($this->all as $all):?>
               <tr  align="center">
                    <td>  <?php echo $all->getIdalocacaoequipamento();?> </td>
                    <td><?php echo $all->getColaborador();?> </td>
                    <td><?php echo $all->getSetor();?> </td>
                    <td><?php echo $all->getLocal();?> </td>
                    <td> <?php echo $all->getDatainicio() ? $all->getDatainicio(): '';?></td>
                    <td> <?php echo $all->getDatafim() ? $all->getDatainicio(): '';;?></td>
                    <td> <?php echo $all->getRealocacao();?></td>
                    <td> <?php echo $all->getObservacao();?></td>
                    <td><a href="<?php echo $this->url('ti/equipamentos/get-detalhe',array('id'=>$all->getEquipamentoFk()->getIdequipamento()));?>"><?php  $nome = "IRM/";
        
        $nome .= "{$all->getEquipamentoFk()->getModeloequipamento()->getTipoequipamento()->getSigla()}/";
        $nome .= "{$all->getEquipamentoFk()->getNome()}";
        echo $nome;;?> </a></td>
                
                    <td>
                        <a data-toggle="tooltip" title="Realocar"   href="<?php echo $this->url('ti/alocacao/store');?>" class="btn btn-mini"><i class="icon-repeat"></i></a>
                        <a data-toggle="tooltip" title="Terminar alocação"   href="<?php echo $this->url('ti/alocacao/termina',array('id'=>$all->getIdalocacaoequipamento()));?>" class="btn btn-mini"><i class="icon-remove"></i></a>
                    </td>
                   
                </tr>
  <?php endforeach;?>
            </tbody>
            <tfoot>
                <tr  align="center">
                    <td colspan="10" >
                       
                        <a data-toggle="tooltip" title="Adicionar registro"   href="<?php echo $this->url('ti/alocacao/store');?>" class="btn btn-primary"><i class="icon-plus icon-white"></i></a>
                    </td>
                   
                </tr>
            </tfoot>

        </table>
    </div>
</div>