<script>
    $(document).ready(function() {
        $("table a").tooltip();
    });
</script>
<?php if ($this->messages):
    ?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>       
    <?php foreach ($this->messages as $messages): ?>
            <strong>Success!</strong> <?php echo $messages ?>       
    <?php endforeach; ?>
    </div>
<?php endif; ?>
<div class="row-fluid">

    <div class="span3">
        <?php
        
        include_once(__DIR__ . '/../menu.phtml'); ?>

    </div>
    <div class="span9">
        <table class="table table-striped table-bordered table-hover">
            <thead>         
                <tr>
                   
                    <th>Fabricante</th>
                    <th>Observação</th>
                   
                    <th>Opções</th>

                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->fab as $usuario): ?>
                    <tr>
                       
                        <td><?php echo $usuario->getFabricante(); ?></td>
                        <td><?php echo $usuario->getObservacao(); ?></td>
                      
                        <td> <a href="<?php echo $this->url('ti/fabricantes/store',array('id'=>$usuario->getIdfabricantes()));?>" data-toggle="tooltip" title="Editar registro"  class="btn"><i class="icon-pencil"></i></a></td>


                    </tr>
                <?php endforeach; ?>

            </tbody>
            <tfoot>
                <tr  align="center">
                    <td colspan="3" >
                       
                        <a data-toggle="tooltip" title="Adicionar registro"   href="<?php echo $this->url('ti/fabricantes/store');?>" class="btn btn-primary"><i class="icon-plus icon-white"></i></a>
                    </td>
                   
                </tr>
            </tfoot>

        </table>

    </div>
</div>